/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedLancamentosRouteImport } from './routes/_authenticated/lancamentos'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedCxRouteImport } from './routes/_authenticated/cx'
import { Route as AuthenticatedConsultiveRouteImport } from './routes/_authenticated/consultive'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedCxEmpresaIdRouteImport } from './routes/_authenticated/cx.$empresaId'
import { Route as AuthenticatedConsultiveEmpresaIdRouteImport } from './routes/_authenticated/consultive.$empresaId'
import { Route as AuthenticatedConciliacaoEmpresaIdRouteImport } from './routes/_authenticated/conciliacao.$empresaId'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedKnowledgeProcessoCodigoRouteImport } from './routes/_authenticated/knowledge.processo.$codigo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLancamentosRoute =
  AuthenticatedLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCxRoute = AuthenticatedCxRouteImport.update({
  id: '/cx',
  path: '/cx',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultiveRoute = AuthenticatedConsultiveRouteImport.update({
  id: '/consultive',
  path: '/consultive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCxEmpresaIdRoute =
  AuthenticatedCxEmpresaIdRouteImport.update({
    id: '/$empresaId',
    path: '/$empresaId',
    getParentRoute: () => AuthenticatedCxRoute,
  } as any)
const AuthenticatedConsultiveEmpresaIdRoute =
  AuthenticatedConsultiveEmpresaIdRouteImport.update({
    id: '/$empresaId',
    path: '/$empresaId',
    getParentRoute: () => AuthenticatedConsultiveRoute,
  } as any)
const AuthenticatedConciliacaoEmpresaIdRoute =
  AuthenticatedConciliacaoEmpresaIdRouteImport.update({
    id: '/$empresaId',
    path: '/$empresaId',
    getParentRoute: () => AuthenticatedConciliacaoRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const AuthenticatedKnowledgeProcessoCodigoRoute =
  AuthenticatedKnowledgeProcessoCodigoRouteImport.update({
    id: '/processo/$codigo',
    path: '/processo/$codigo',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/conciliacao': typeof AuthenticatedConciliacaoRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consultive': typeof AuthenticatedConsultiveRouteWithChildren
  '/cx': typeof AuthenticatedCxRouteWithChildren
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/conciliacao/$empresaId': typeof AuthenticatedConciliacaoEmpresaIdRoute
  '/consultive/$empresaId': typeof AuthenticatedConsultiveEmpresaIdRoute
  '/cx/$empresaId': typeof AuthenticatedCxEmpresaIdRoute
  '/knowledge/processo/$codigo': typeof AuthenticatedKnowledgeProcessoCodigoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/conciliacao': typeof AuthenticatedConciliacaoRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consultive': typeof AuthenticatedConsultiveRouteWithChildren
  '/cx': typeof AuthenticatedCxRouteWithChildren
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/conciliacao/$empresaId': typeof AuthenticatedConciliacaoEmpresaIdRoute
  '/consultive/$empresaId': typeof AuthenticatedConsultiveEmpresaIdRoute
  '/cx/$empresaId': typeof AuthenticatedCxEmpresaIdRoute
  '/knowledge/processo/$codigo': typeof AuthenticatedKnowledgeProcessoCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/consultive': typeof AuthenticatedConsultiveRouteWithChildren
  '/_authenticated/cx': typeof AuthenticatedCxRouteWithChildren
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/_authenticated/lancamentos': typeof AuthenticatedLancamentosRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/conciliacao/$empresaId': typeof AuthenticatedConciliacaoEmpresaIdRoute
  '/_authenticated/consultive/$empresaId': typeof AuthenticatedConsultiveEmpresaIdRoute
  '/_authenticated/cx/$empresaId': typeof AuthenticatedCxEmpresaIdRoute
  '/_authenticated/knowledge/processo/$codigo': typeof AuthenticatedKnowledgeProcessoCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/consultive'
    | '/cx'
    | '/documentos'
    | '/knowledge'
    | '/lancamentos'
    | '/tarefas'
    | '/clientes/$id'
    | '/conciliacao/$empresaId'
    | '/consultive/$empresaId'
    | '/cx/$empresaId'
    | '/knowledge/processo/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/consultive'
    | '/cx'
    | '/documentos'
    | '/knowledge'
    | '/lancamentos'
    | '/tarefas'
    | '/clientes/$id'
    | '/conciliacao/$empresaId'
    | '/consultive/$empresaId'
    | '/cx/$empresaId'
    | '/knowledge/processo/$codigo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/clientes'
    | '/_authenticated/conciliacao'
    | '/_authenticated/configuracoes'
    | '/_authenticated/consultive'
    | '/_authenticated/cx'
    | '/_authenticated/documentos'
    | '/_authenticated/knowledge'
    | '/_authenticated/lancamentos'
    | '/_authenticated/tarefas'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/conciliacao/$empresaId'
    | '/_authenticated/consultive/$empresaId'
    | '/_authenticated/cx/$empresaId'
    | '/_authenticated/knowledge/processo/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos': {
      id: '/_authenticated/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AuthenticatedLancamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cx': {
      id: '/_authenticated/cx'
      path: '/cx'
      fullPath: '/cx'
      preLoaderRoute: typeof AuthenticatedCxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultive': {
      id: '/_authenticated/consultive'
      path: '/consultive'
      fullPath: '/consultive'
      preLoaderRoute: typeof AuthenticatedConsultiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cx/$empresaId': {
      id: '/_authenticated/cx/$empresaId'
      path: '/$empresaId'
      fullPath: '/cx/$empresaId'
      preLoaderRoute: typeof AuthenticatedCxEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedCxRoute
    }
    '/_authenticated/consultive/$empresaId': {
      id: '/_authenticated/consultive/$empresaId'
      path: '/$empresaId'
      fullPath: '/consultive/$empresaId'
      preLoaderRoute: typeof AuthenticatedConsultiveEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedConsultiveRoute
    }
    '/_authenticated/conciliacao/$empresaId': {
      id: '/_authenticated/conciliacao/$empresaId'
      path: '/$empresaId'
      fullPath: '/conciliacao/$empresaId'
      preLoaderRoute: typeof AuthenticatedConciliacaoEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedConciliacaoRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/knowledge/processo/$codigo': {
      id: '/_authenticated/knowledge/processo/$codigo'
      path: '/processo/$codigo'
      fullPath: '/knowledge/processo/$codigo'
      preLoaderRoute: typeof AuthenticatedKnowledgeProcessoCodigoRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedConciliacaoRouteChildren {
  AuthenticatedConciliacaoEmpresaIdRoute: typeof AuthenticatedConciliacaoEmpresaIdRoute
}

const AuthenticatedConciliacaoRouteChildren: AuthenticatedConciliacaoRouteChildren =
  {
    AuthenticatedConciliacaoEmpresaIdRoute:
      AuthenticatedConciliacaoEmpresaIdRoute,
  }

const AuthenticatedConciliacaoRouteWithChildren =
  AuthenticatedConciliacaoRoute._addFileChildren(
    AuthenticatedConciliacaoRouteChildren,
  )

interface AuthenticatedConsultiveRouteChildren {
  AuthenticatedConsultiveEmpresaIdRoute: typeof AuthenticatedConsultiveEmpresaIdRoute
}

const AuthenticatedConsultiveRouteChildren: AuthenticatedConsultiveRouteChildren =
  {
    AuthenticatedConsultiveEmpresaIdRoute:
      AuthenticatedConsultiveEmpresaIdRoute,
  }

const AuthenticatedConsultiveRouteWithChildren =
  AuthenticatedConsultiveRoute._addFileChildren(
    AuthenticatedConsultiveRouteChildren,
  )

interface AuthenticatedCxRouteChildren {
  AuthenticatedCxEmpresaIdRoute: typeof AuthenticatedCxEmpresaIdRoute
}

const AuthenticatedCxRouteChildren: AuthenticatedCxRouteChildren = {
  AuthenticatedCxEmpresaIdRoute: AuthenticatedCxEmpresaIdRoute,
}

const AuthenticatedCxRouteWithChildren = AuthenticatedCxRoute._addFileChildren(
  AuthenticatedCxRouteChildren,
)

interface AuthenticatedKnowledgeRouteChildren {
  AuthenticatedKnowledgeProcessoCodigoRoute: typeof AuthenticatedKnowledgeProcessoCodigoRoute
}

const AuthenticatedKnowledgeRouteChildren: AuthenticatedKnowledgeRouteChildren =
  {
    AuthenticatedKnowledgeProcessoCodigoRoute:
      AuthenticatedKnowledgeProcessoCodigoRoute,
  }

const AuthenticatedKnowledgeRouteWithChildren =
  AuthenticatedKnowledgeRoute._addFileChildren(
    AuthenticatedKnowledgeRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConsultiveRoute: typeof AuthenticatedConsultiveRouteWithChildren
  AuthenticatedCxRoute: typeof AuthenticatedCxRouteWithChildren
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRouteWithChildren
  AuthenticatedLancamentosRoute: typeof AuthenticatedLancamentosRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConsultiveRoute: AuthenticatedConsultiveRouteWithChildren,
  AuthenticatedCxRoute: AuthenticatedCxRouteWithChildren,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRouteWithChildren,
  AuthenticatedLancamentosRoute: AuthenticatedLancamentosRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
